services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.3
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow/mlruns:/mlruns
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri /mlruns
      --default-artifact-root /mlruns
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 15s
      timeout: 10s
      retries: 10

  inference_api:
    build: ./services/inference_api
    ports:
      - "8002:8000"
    volumes:
      - ./data:/data
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      mlflow:
        condition: service_healthy

  feedback_api:
    build: ./services/feedback_api
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy

  feature_pipeline:
    build: ./services/feature_pipeline
    volumes:
      - ./data:/data
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy

  scheduler:
    build: ./services/scheduler
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy

  trainer:
    build: ./services/trainer
    volumes:
      - ./data:/data
    env_file: .env
    environment:
      - INFERENCE_API_URL=http://inference_api:8000
    depends_on:
      redis:
        condition: service_healthy
      mlflow:
        condition: service_healthy


  ui:
    build: ./services/ui
    ports:
      - "3000:80"
    depends_on:
      - inference_api
      - feedback_api
